# Generated by Django 5.0.7 on 2024-10-10 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Aplicacion', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuarios',
            name='ApeUsu',
        ),
        migrations.RemoveField(
            model_name='usuarios',
            name='EmailUsu',
        ),
        migrations.RemoveField(
            model_name='usuarios',
            name='NomUsu',
        ),
        migrations.RemoveField(
            model_name='usuarios',
            name='RutUsu',
        ),
        migrations.RemoveField(
            model_name='usuarios',
            name='id',
        ),
        migrations.AddField(
            model_name='usuarios',
            name='Apellido',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usuarios',
            name='Email',
            field=models.EmailField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usuarios',
            name='Nombre',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usuarios',
            name='Rut',
            field=models.CharField(default=1, max_length=12, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='usuarios',
            name='Contraseña',
            field=models.CharField(max_length=100),
        ),
    ]
