# Generated by Django 5.0.7 on 2024-11-18 02:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Aplicacion', '0002_remove_usuarios_apeusu_remove_usuarios_emailusu_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cursos',
            name='Categoria',
            field=models.CharField(default='Desconocida', max_length=50),
        ),
        migrations.AddField(
            model_name='cursos',
            name='DesDet',
            field=models.TextField(default='Desconocida', verbose_name=800),
        ),
        migrations.AddField(
            model_name='cursos',
            name='Dificultad',
            field=models.CharField(default='Desconocida', max_length=50),
        ),
        migrations.AddField(
            model_name='cursos',
            name='NumUnidades',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cursos',
            name='Autor',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='cursos',
            name='Descripcion',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='cursos',
            name='Duracion',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='cursos',
            name='NCurso',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='cursos',
            name='Total',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.CreateModel(
            name='Unidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('contenido', models.TextField()),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unidades', to='Aplicacion.cursos')),
            ],
        ),
    ]
