# Generated by Django 5.0.7 on 2024-11-24 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Aplicacion', '0003_cursos_categoria_cursos_desdet_cursos_dificultad_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cursos',
            name='FotoPortada',
            field=models.ImageField(blank=True, null=True, upload_to='Portadas/'),
        ),
    ]
