# Generated by Django 5.0.7 on 2024-11-25 02:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Aplicacion', '0004_cursos_fotoportada'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cursos',
            old_name='FotoPortada',
            new_name='ImagenPortada',
        ),
    ]
