# Generated by Django 5.0.7 on 2024-11-25 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Aplicacion', '0005_rename_fotoportada_cursos_imagenportada'),
    ]

    operations = [
        migrations.AddField(
            model_name='unidad',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='unidades_imagenes/'),
        ),
    ]
