# Generated by Django 5.0.7 on 2024-12-12 07:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Aplicacion', '0007_comentario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comentario',
            name='curso',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Comentarios', to='Aplicacion.cursos'),
        ),
    ]
